//! The privileged Ethos-zero wire contract, spoken on the meta socket of the
//! Ethos Nexus that follows ethos-zero.
//!
//! `ethos/signal.ethos` is the authored source and the only interface;
//! `src/generated/signal.rs` is its projection, regenerated by ethos-zero and
//! held byte-identical by `build.rs`. The names it shares with the ordinary
//! contract (`RelativePath`, `FileLocation`) come from signal-ethos-zero's
//! Library, imported as `signal_ethos_zero:[ … ]`.
//!
//! The contract rides signal's exchange layer. Its identity on the wire is
//! the digest of the Library and its own source, settled once per connection
//! by the greeting; two peers built from different sources refuse each other
//! rather than negotiate. The framing, the greeting and the exchange envelope
//! are signal's; this crate holds vocabulary only.

pub mod generated;
pub use generated::signal::*;
pub use signal_ethos_zero::{FileLocation, RelativePath, SourceName};

/// The authored Ethos source this contract is generated from.
pub const ETHOS: &str = include_str!("../ethos/signal.ethos");

/// The one artefact the wire identity is computed over: signal-ethos-zero's
/// Library, which `ETHOS` imports, followed by `ETHOS`.
pub const CONTRACT: &str = include_str!(concat!(env!("OUT_DIR"), "/contract.ethos"));

/// The querying side is the side that greets, so the identity is borne by
/// the query root.
impl signal::Contracted for Query {
    const CONTRACT_SOURCE: &'static str = CONTRACT;
}
